### ISSUE TITLE
tracks are missing in the directory listing

### ISSUE THREAD

**Issue by rjayasinghe** [volumio/Volumio-WebUI#17]
I have one (or even more) artists' directory in my music library that contain one or more directories for the albums. When I open the album in the library/browse view of Volumio I cannot see any tracks listed. If I choose to add that album/directory to the current playlist the tracks appeear on the playlist. Is this behavior known? I guess that this is not intended. ;)

Best Regards,
Robin

**Comment by ning-yu** [comment]
Closing old issue - please open another if this is still happening!
