### ISSUE TITLE
Running on Ubuntu

### ISSUE THREAD

**Issue by steveww** [volumio/Volumio-WebUI#18]
I have attempted to set this up on Ubuntu 14.04 LTS.

I copied over the config files from _OS_SETTINGS, fixed the IPV6 config issue.

Alas my browser just shows an empty page and there is nothing in the nginx error log (set to info level). Any hints and tips on how to debug this?

Is there any additional logging I can use to see what is breaking?

**Comment by ning-yu** [comment]
Volumio 1.X is an entire OS and software package (lots of configuration changes and customizations). At this time it is not possible to install it on an existing system.
