### ISSUE TITLE
Running webuiupdate.sh breaks shairport

### ISSUE THREAD

**Issue by rjayasinghe** [volumio/Volumio-WebUI#19]
Shairport/Airplay was working with the downloaded image. After running webuiupdate.sh the service did not start anymore. It seems that the options provided in the script do not work with the upgraded shairport (just a blind guess)..

Removing the -w flag does the job BTW. The usage documentation of shairport does not list this option as of the latest version.. 

Best Regards,
Robin

**Comment by ning-yu** [comment]
Fixed
