### ISSUE TITLE
Volume control from android web browser

### ISSUE THREAD

**Issue by p3trus** [volumio/Volumio-WebUI#28]
I installed the lates version from the website. When im changing the volume from my laptop everything works fine. Using an android phone, it's unusable. The webpage does not fit the whole screen so I have to scroll. This sometimes changes the volume. But that is not the huge problem. Changing the volume itself is. When im clicking somewhere on the circle, the volume jumps to 100% and after a few seconds to the clicked volume. It's not just the gui I can actually hear it.

**Comment by ning-yu** [comment]
Closing old ticket. Please open a new one if this is still happening!
