### ISSUE TITLE
Bug on reading files containing ":"

### ISSUE THREAD

**Issue by jotak** [volumio/Volumio-WebUI#39]
cf http://volumio.org/forum/colons-directory-and-file-names-cause-trouble-t1823.html#p7444
https://github.com/volumio/Volumio-WebUI/blob/master/inc/player_lib.php#L301

need to change to
"list ( $element, $value ) = explode(": ", $plistLine, 2);"

Same error exist line 103

**Comment by ning-yu** [comment]
Appears to be fixed.
