### ISSUE TITLE
Spotify playlist not visible in 'playlist'

### ISSUE THREAD

**Issue by Atrejoe** [volumio/Volumio-WebUI#49]
Is this the way it was meant to be? I Spotify queue management pending implementation?

![image](https://cloud.githubusercontent.com/assets/585091/4890042/3fa0338a-639b-11e4-97b4-e24906b7cbe0.png)

![image](https://cloud.githubusercontent.com/assets/585091/4890046/486d685c-639b-11e4-8d14-06983e8e7583.png)

**Comment by rriemann** [comment]
Any progress on this issue?

**Comment by ning-yu** [comment]
I am currently helping to write Volumio 2.0, This has a playlist system capable of manipulating tracks from all sources (current and future services included), among other new features. There might be a couple more Volumio 1 releases before we can get this out the door, however!

**Comment by DieterKoblenz** [comment]
Any ETA on this feature? I'm trying to get my girlfriend use Volumio but this is still a bridge too far ;)
