### ISSUE TITLE
Can't Read Text Entry Fields, They Are White On White

### ISSUE THREAD

**Issue by gbmhunter** [volumio/Volumio-WebUI#59]
See the image below for an example. There is actually text entered into the "Spotify Username" field, you just can't see it because it is white on white. Highlighting the text makes it visible (this is how I know there is actually text there).

![volumio-text-entry-fields-white-on-white](https://cloud.githubusercontent.com/assets/2396869/5566804/93fecbb6-8f98-11e4-907c-0866ebe8e8d2.png)

Using Volumio v1.51 on a RaspberrPi B+ and viewing the WebUI with Chrome. This applies to most text-entry fields in the WebUI.

A simple CSS bug?

**Comment by ning-yu** [comment]
I see white on black (or very near black). Can you right click the box in Chrome, and hit Inspect Element? That will tell you what CSS is driving the white color.

**Comment by ning-yu** [comment]
I can't reproduce this issue. Open a new ticket if you see this again, and attach the results of Chrome Inspect Element.
