### ISSUE TITLE
missing menu entry to delete items

### ISSUE THREAD

**Issue by quantenschaum** [volumio/Volumio-WebUI#64]
It is impossible to delete library items like radio stations or playlists through the web UI.

A radio station can be deleted by deleting the corresponding file via SMB, but how to delete a saved playlist?

**Comment by joh-klein** [comment]
I was wondering about the same thing. So, can we get this fixed, please?

**Comment by joh-klein** [comment]
I deleted most of the stations via SSH. They are stored in `/var/lib/mpd/music/WEBRADIO`
