### ISSUE TITLE
Running WebUI on xampp

### ISSUE THREAD

**Issue by DrChills** [volumio/Volumio-WebUI#71]
Hi,

I am trying to run the webUI on localhost to start playing with the code - however I am getting an error from player_lib : stream_socket_client(): unable to connect

I have commented / uncommented the code config.inc 

any help would be great as I would like to start helping with the project

**Comment by ning-yu** [comment]
it might be having problems connecting to MPD or Spop. Are both MPD and Spop running?

**Comment by ning-yu** [comment]
Closing due to no response.
