### ISSUE TITLE
Add support for MPD satellite mode

### ISSUE THREAD

**Issue by jinnko** [volumio/Volumio-WebUI#74]
Using Volumio on embedded devices often comes with less storage.  With the satellite mode supported by MPD it is possible to have multiple devices all using a central MPD database.

The MPD documentation shows it's very easy to configure this.
http://www.musicpd.org/doc/user/advanced_config.html#satellite

Would be great to have this supported in the UI.

**Comment by ning-yu** [comment]
Sounds interesting! If I understand correctly, MPD would be running on the storage server just to maintain the library, and the MPD on your playback device is the one reading the file and playing it?

**Comment by jinnko** [comment]
Correct.  This has the added benefit that if you have multiple satellites you only need to update the db once on the central fileserver.

**Comment by ning-yu** [comment]
Pushing this feature over to Volumio 2, where we'll properly implement this into the UI
