### ISSUE TITLE
New parameters for mpd.config

### ISSUE THREAD

**Issue by norrest** [volumio/Volumio-WebUI#83]
Hi! How add new parameters in mpd.config  of use WEB-ui?
Its use in player.db ->>>> *.php  ->>>>  /etc/mpd.conf

**Comment by volumio** [comment]
No, it's this file: https://github.com/volumio/Volumio-WebUI/blob/master/inc/player_lib.php

However, if you want to develop new functionalities, please take a look at Volumio2
https://github.com/volumio/Volumio2

**Comment by norrest** [comment]
look -> this parameters parse from db file!

// parse DB output
	foreach ($mpdcfg as $cfg) {
		if ($cfg['param'] == 'audio_output_format' && $cfg['value_player'] == 'disabled'){
		$output .= '';
		} else if ($cfg['param'] == 'dop') {
		$dop = $cfg['value_player'];
		} else if ($cfg['param'] == 'device') {
		$device = $cfg['value_player'];
		var_export($device);
		// $output .= '';
		} else if ($cfg['param'] == 'mixer_type' && $cfg['value_player'] == 'hardware' ) { 
		// $hwmixer['device'] = 'hw:0';
		$hwmixer['control'] = alsa_findHwMixerControl($device);
		// $hwmixer['index'] = '1';
		}  else {
		$output .= $cfg['param']." \t\"".$cfg['value_player']."\"\n";
		}
	}

**Comment by norrest** [comment]
in player.db 

82	optional_alsa_output_parameters	dop	__yes or no__	enable DSD audio support.	no	no
