### ISSUE TITLE
Dropdown menu opens an "undefined" location

### ISSUE THREAD

**Issue by mamuesp** [volumio/Volumio-WebUI#9]
in "links.js" there is a bug, which will results in the malfunction of the dropdown menues.

At line 12 of the file, the element's href is only checked not to be NULL, but an undefined value will be accepted. So in the dropdown menus, after selecting an entry, the result is an 404 HTML error, because the location.href is set to the value "undefined".

When the following lines (12 to 17):
...
            if (!$(event.target).attr("href")) {
                location.href = $(event.target).parent().attr("href");
            } else {
                location.href = $(event.target).attr("href");
            }
        } else {}
...

will be replaced by these corrected lines, it works correctly:
...
            elem = $(event.target);
            newHref = $(event.target).attr("href");
            if (newHref === undefined || !newHref || newHref === "") {
                newHref = elem.parent().attr("href");
            }
            if (!(newHref === undefined || !newHref || newHref === "")}
            {
                location.href = newHref;
            }
...

After the change, the location.href will not be changed, if the href attribute of the event.target and the one of its parent is not useable (NULL, undefined or empty string). Tested on FireFox and iPhone 4s (iOS 7).

**Comment by ning-yu** [comment]
Please open a new ticket if you see this happen in actual use. I have not seen this happen yet.
